# Generated by Django 3.2.2 on 2021-05-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaformapp', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
